### ISSUE TITLE
Can't install plugin (decky)

### ISSUE THREAD

**Issue by PabloSimplistic** [wheaney/decky-XRGaming#38]
Hi everyone! I'm running cachyos and whenever I try to install the XR plugin, I get an error telling me that it couldn't be installed. 

I can install other plugins without issue, but wanted to know if there's any workaround or prerequisite I might be missing

**Comment by wheaney** [comment]
Hi, I haven't heard of CachyOS before this, so you may be the first to try it and it's likely the cause of the issue. The first step would be looking at the logs, you can please provide the latest logs in `~/homebrew/logs/decky-XRGaming/`.

**Comment by wheaney** [comment]
Also show me what you see when you do this command from a terminal:
> su -l -c 'XDG_RUNTIME_DIR=/run/user/1000 systemctl --user is-active xr-driver' deck

**Comment by PabloSimplistic** [comment]
it says "inactive" [user is deck, same as steam deck]

**Comment by wheaney** [comment]
Please see my previous message requesting logs.

**Comment by PabloSimplistic** [comment]
I don't see any homebrew folder sadly.

**Comment by PabloSimplistic** [comment]
Sorry, found the logs!

`[2024-12-15 03:26:57,457][INFO]: Installing breezy for plugin version 1.0.2
[2024-12-15 03:26:58,659][ERROR]: Error running setup script: b"Created temp directory: /tmp/breezy-vulkan-AmeCl7dh5r\nExtracting to: /tmp/breezy-vulkan-AmeCl7dh5r/breezy_vulkan\nCleaning up the previous installation\nCopying the breezy_vulkan scripts to /home/deck/.local/bin and related files to /home/deck/.local/share/breezy_vulkan\nInstalling vkBasalt; copying binaries, configs, and shader files\nInstalling the Sombrero shader and texture files to /home/deck/.config/reshade/{Shaders,Textures} and /home/deck/.local/share/gamescope/reshade/{Shaders,Textures}\nInstalling xrDriver\nBEGIN - xr_driver_setup\nCreated temp directory: /tmp/xr-driver-JYpc7rnGOR\nExtracting to: /tmp/xr-driver-JYpc7rnGOR/xr_driver\nCleaning up the previous installation\nChanging ownership of /tmp/xr-driver-JYpc7rnGOR to deck:deck\nflatpak: /tmp/_MEIJOteXw/libcrypto.so.3: version `OPENSSL_3.4.0' not found (required by /usr/lib/libostree-1.so.1)\nflatpak: /tmp/_MEIJOteXw/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /usr/lib/libcurl.so.4)\nflatpak: /tmp/_MEIJOteXw/libssl.so.3: version `OPENSSL_3.3.0' not found (required by /usr/lib/libcurl.so.4)\nsystemctl: /tmp/_MEIJOteXw/libcrypto.so.3: version `OPENSSL_3.4.0' not found (required by /usr/lib/systemd/libsystemd-shared-257-1.so)\nCopying shared libraries to /home/deck/.local/share/xr_driver/lib\nCopying driver binary and scripts to /home/deck/.local/bin and /home/deck/.local/share/xr_driver\nCopying the systemd service to /home/deck/.local/share/systemd/user\nCopying the udev rules to /usr/lib/udev/rules.d\nudevadm: /tmp/_MEIJOteXw/libcrypto.so.3: version `OPENSSL_3.4.0' not found (required by /usr/lib/systemd/libsystemd-shared-257-1.so)\n"
[2024-12-15 03:27:00,166][ERROR]: Error running setup script: b"Created temp directory: /tmp/breezy-vulkan-FRd2m0PK7N\nExtracting to: /tmp/breezy-vulkan-FRd2m0PK7N/breezy_vulkan\nCleaning up the previous installation\nCopying the breezy_vulkan scripts to /home/deck/.local/bin and related files to /home/deck/.local/share/breezy_vulkan\nInstalling vkBasalt; copying binaries, configs, and shader files\nInstalling the Sombrero shader and texture files to /home/deck/.config/reshade/{Shaders,Textures} and /home/deck/.local/share/gamescope/reshade/{Shaders,Textures}\nInstalling xrDriver\nBEGIN - xr_driver_setup\nCreated temp directory: /tmp/xr-driver-JbN9Ythj2g\nExtracting to: /tmp/xr-driver-JbN9Ythj2g/xr_driver\nCleaning up the previous installation\nChanging ownership of /tmp/xr-driver-JbN9Ythj2g to deck:deck\nflatpak: /tmp/_MEIJOteXw/libcrypto.so.3: version `OPENSSL_3.4.0' not found (required by /usr/lib/libostree-1.so.1)\nflatpak: /tmp/_MEIJOteXw/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /usr/lib/libcurl.so.4)\nflatpak: /tmp/_MEIJOteXw/libssl.so.3: version `OPENSSL_3.3.0' not found (required by /usr/lib/libcurl.so.4)\nsystemctl: /tmp/_MEIJOteXw/libcrypto.so.3: version `OPENSSL_3.4.0' not found (required by /usr/lib/systemd/libsystemd-shared-257-1.so)\nCopying shared libraries to /home/deck/.local/share/xr_driver/lib\nCopying driver binary and scripts to /home/deck/.local/bin and /home/deck/.local/share/xr_driver\nCopying the systemd service to /home/deck/.local/share/systemd/user\nCopying the udev rules to /usr/lib/udev/rules.d\nudevadm: /tmp/_MEIJOteXw/libcrypto.so.3: version `OPENSSL_3.4.0' not found (required by /usr/lib/systemd/libsystemd-shared-257-1.so)\n"
[2024-12-15 03:27:02,041][ERROR]: Error running setup script: b"Created temp directory: /tmp/breezy-vulkan-rsOzxQwFLO\nExtracting to: /tmp/breezy-vulkan-rsOzxQwFLO/breezy_vulkan\nCleaning up the previous installation\nCopying the breezy_vulkan scripts to /home/deck/.local/bin and related files to /home/deck/.local/share/breezy_vulkan\nInstalling vkBasalt; copying binaries, configs, and shader files\nInstalling the Sombrero shader and texture files to /home/deck/.config/reshade/{Shaders,Textures} and /home/deck/.local/share/gamescope/reshade/{Shaders,Textures}\nInstalling xrDriver\nBEGIN - xr_driver_setup\nCreated temp directory: /tmp/xr-driver-6FIHd2PGKh\nExtracting to: /tmp/xr-driver-6FIHd2PGKh/xr_driver\nCleaning up the previous installation\nChanging ownership of /tmp/xr-driver-6FIHd2PGKh to deck:deck\nflatpak: /tmp/_MEIJOteXw/libcrypto.so.3: version `OPENSSL_3.4.0' not found (required by /usr/lib/libostree-1.so.1)\nflatpak: /tmp/_MEIJOteXw/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /usr/lib/libcurl.so.4)\nflatpak: /tmp/_MEIJOteXw/libssl.so.3: version `OPENSSL_3.3.0' not found (required by /usr/lib/libcurl.so.4)\nsystemctl: /tmp/_MEIJOteXw/libcrypto.so.3: version `OPENSSL_3.4.0' not found (required by /usr/lib/systemd/libsystemd-shared-257-1.so)\nCopying shared libraries to /home/deck/.local/share/xr_driver/lib\nCopying driver binary and scripts to /home/deck/.local/bin and /home/deck/.local/share/xr_driver\nCopying the systemd service to /home/deck/.local/share/systemd/user\nCopying the udev rules to /usr/lib/udev/rules.d\nudevadm: /tmp/_MEIJOteXw/libcrypto.so.3: version `OPENSSL_3.4.0' not found (required by /usr/lib/systemd/libsystemd-shared-257-1.so)\n"
[2024-12-15 03:27:23,762][INFO]: Installing breezy for plugin version 1.0.2
[2024-12-15 03:27:24,634][ERROR]: Error running setup script: b"Created temp directory: /tmp/breezy-vulkan-rxRA9OV7LU\nExtracting to: /tmp/breezy-vulkan-rxRA9OV7LU/breezy_vulkan\nCleaning up the previous installation\nCopying the breezy_vulkan scripts to /home/deck/.local/bin and related files to /home/deck/.local/share/breezy_vulkan\nInstalling vkBasalt; copying binaries, configs, and shader files\nInstalling the Sombrero shader and texture files to /home/deck/.config/reshade/{Shaders,Textures} and /home/deck/.local/share/gamescope/reshade/{Shaders,Textures}\nInstalling xrDriver\nBEGIN - xr_driver_setup\nCreated temp directory: /tmp/xr-driver-I1FzLmmfRL\nExtracting to: /tmp/xr-driver-I1FzLmmfRL/xr_driver\nCleaning up the previous installation\nChanging ownership of /tmp/xr-driver-I1FzLmmfRL to deck:deck\nflatpak: /tmp/_MEIJOteXw/libcrypto.so.3: version `OPENSSL_3.4.0' not found (required by /usr/lib/libostree-1.so.1)\nflatpak: /tmp/_MEIJOteXw/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /usr/lib/libcurl.so.4)\nflatpak: /tmp/_MEIJOteXw/libssl.so.3: version `OPENSSL_3.3.0' not found (required by /usr/lib/libcurl.so.4)\nsystemctl: /tmp/_MEIJOteXw/libcrypto.so.3: version `OPENSSL_3.4.0' not found (required by /usr/lib/systemd/libsystemd-shared-257-1.so)\nCopying shared libraries to /home/deck/.local/share/xr_driver/lib\nCopying driver binary and scripts to /home/deck/.local/bin and /home/deck/.local/share/xr_driver\nCopying the systemd service to /home/deck/.local/share/systemd/user\nCopying the udev rules to /usr/lib/udev/rules.d\nudevadm: /tmp/_MEIJOteXw/libcrypto.so.3: version `OPENSSL_3.4.0' not found (required by /usr/lib/systemd/libsystemd-shared-257-1.so)\n"
[2024-12-15 03:27:26,024][ERROR]: Error running setup script: b"Created temp directory: /tmp/breezy-vulkan-9PFHWEq7h8\nExtracting to: /tmp/breezy-vulkan-9PFHWEq7h8/breezy_vulkan\nCleaning up the previous installation\nCopying the breezy_vulkan scripts to /home/deck/.local/bin and related files to /home/deck/.local/share/breezy_vulkan\nInstalling vkBasalt; copying binaries, configs, and shader files\nInstalling the Sombrero shader and texture files to /home/deck/.config/reshade/{Shaders,Textures} and /home/deck/.local/share/gamescope/reshade/{Shaders,Textures}\nInstalling xrDriver\nBEGIN - xr_driver_setup\nCreated temp directory: /tmp/xr-driver-59VQ7fv1dN\nExtracting to: /tmp/xr-driver-59VQ7fv1dN/xr_driver\nCleaning up the previous installation\nChanging ownership of /tmp/xr-driver-59VQ7fv1dN to deck:deck\nflatpak: /tmp/_MEIJOteXw/libcrypto.so.3: version `OPENSSL_3.4.0' not found (required by /usr/lib/libostree-1.so.1)\nflatpak: /tmp/_MEIJOteXw/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /usr/lib/libcurl.so.4)\nflatpak: /tmp/_MEIJOteXw/libssl.so.3: version `OPENSSL_3.3.0' not found (required by /usr/lib/libcurl.so.4)\nsystemctl: /tmp/_MEIJOteXw/libcrypto.so.3: version `OPENSSL_3.4.0' not found (required by /usr/lib/systemd/libsystemd-shared-257-1.so)\nCopying shared libraries to /home/deck/.local/share/xr_driver/lib\nCopying driver binary and scripts to /home/deck/.local/bin and /home/deck/.local/share/xr_driver\nCopying the systemd service to /home/deck/.local/share/systemd/user\nCopying the udev rules to /usr/lib/udev/rules.d\nudevadm: /tmp/_MEIJOteXw/libcrypto.so.3: version `OPENSSL_3.4.0' not found (required by /usr/lib/systemd/libsystemd-shared-257-1.so)\n"
[2024-12-15 03:27:27,793][ERROR]: Error running setup script: b"Created temp directory: /tmp/breezy-vulkan-qgMwXvLxOs\nExtracting to: /tmp/breezy-vulkan-qgMwXvLxOs/breezy_vulkan\nCleaning up the previous installation\nCopying the breezy_vulkan scripts to /home/deck/.local/bin and related files to /home/deck/.local/share/breezy_vulkan\nInstalling vkBasalt; copying binaries, configs, and shader files\nInstalling the Sombrero shader and texture files to /home/deck/.config/reshade/{Shaders,Textures} and /home/deck/.local/share/gamescope/reshade/{Shaders,Textures}\nInstalling xrDriver\nBEGIN - xr_driver_setup\nCreated temp directory: /tmp/xr-driver-CfDrAkkm8I\nExtracting to: /tmp/xr-driver-CfDrAkkm8I/xr_driver\nCleaning up the previous installation\nChanging ownership of /tmp/xr-driver-CfDrAkkm8I to deck:deck\nflatpak: /tmp/_MEIJOteXw/libcrypto.so.3: version `OPENSSL_3.4.0' not found (required by /usr/lib/libostree-1.so.1)\nflatpak: /tmp/_MEIJOteXw/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /usr/lib/libcurl.so.4)\nflatpak: /tmp/_MEIJOteXw/libssl.so.3: version `OPENSSL_3.3.0' not found (required by /usr/lib/libcurl.so.4)\nsystemctl: /tmp/_MEIJOteXw/libcrypto.so.3: version `OPENSSL_3.4.0' not found (required by /usr/lib/systemd/libsystemd-shared-257-1.so)\nCopying shared libraries to /home/deck/.local/share/xr_driver/lib\nCopying driver binary and scripts to /home/deck/.local/bin and /home/deck/.local/share/xr_driver\nCopying the systemd service to /home/deck/.local/share/systemd/user\nCopying the udev rules to /usr/lib/udev/rules.d\nudevadm: /tmp/_MEIJOteXw/libcrypto.so.3: version `OPENSSL_3.4.0' not found (required by /usr/lib/systemd/libsystemd-shared-257-1.so)\n"
[2024-12-15 03:27:39,201][ERROR]: Exception in callback UnixSocket._listen_for_method_call.<locals>._(<Task finishe...eyError('id')>) at decky_loader/localplatform/localsocket.py:120
handle: <Handle UnixSocket._listen_for_method_call.<locals>._(<Task finishe...eyError('id')>) at decky_loader/localplatform/localsocket.py:120>
Traceback (most recent call last):
  File "asyncio/events.py", line 80, in _run
  File "decky_loader/localplatform/localsocket.py", line 121, in _
  File "decky_loader/plugin/sandboxed_plugin.py", line 190, in on_new_message
KeyError: 'id'
[2024-12-15 03:27:39,202][INFO]: Calling Loader unload function for XR Gaming.
[2024-12-15 03:27:39,202][INFO]: Attempting to unload with plugin XR Gaming's "_unload" function.

[2024-12-15 03:27:39,202][INFO]: Unloaded XR Gaming

[2024-12-15 03:27:39,202][INFO]: Calling Loader uninstall function.
[2024-12-15 03:27:39,202][INFO]: Attempting to uninstall with plugin XR Gaming's "_uninstall" function.

[2024-12-15 03:27:39,202][INFO]: Uninstalling breezy for plugin version 1.0.2
[2024-12-15 03:27:39,386][INFO]: Uninstalled XR Gaming

`

**Comment by wheaney** [comment]
Looks like you need to install OpenSSL. Assuming Cachy is Arch based it would probably be solved with `sudo pacman -S openssl`

**Comment by PabloSimplistic** [comment]
Thanks for the help, unfortunately, I've tried but the issue remains, I've checked in my konsole that openssl version is ok, and in fact is there and running 3.4.0, but cannot install the plugin as it tells me that it's not found, idk if it's because it's looking for it in a different path or something like that. Guess I'll have to use the galsses without the plugin until I get a real steam os or move to bazzite.

**Comment by wheaney** [comment]
Can you explain where `flatpak` comes into this? I'm seeing that the error logs about OpenSSL seem to be coming from flatpak but that's not usually part of the installation process.

**Comment by wheaney** [comment]
Also very weird is that all of the errors are coming from a shared library in `/tmp/_MEIJOteXw`. My app isn't creating that directory, why are there libs in that directory, and what created it?

**Comment by aequis** [comment]
I'm getting "tmp/_MEIvJWsf2/libcrypto.so.3: version `OPENSSL_3.4.0' not found (required by /usr/lib/systemd/libsystemd-shared-256.7-1.2.so)" on my Steam Deck (stable branch both in Decky and in SteamOS). Was a solution for this ever found?

**Comment by wheaney** [comment]
@aequis Can you see what version of decky-loader you're using? If you're on the `Prerelease` decky loader channel, then it may be related to [this](https://github.com/SteamDeckHomebrew/decky-loader/issues/756)

**Comment by zhark0vv** [comment]
@wheaney 
Hi there!
Thank you for your work.

I also have a same problem with setup on Cachy OS Legion GO.
Logs are attached.

As for Decky version, the error is reproducing both on Stable/Prerelease branches, also Stable and Beta Steam Client.
So I upgraded version of OPENSSL.

Logs are attached.

[2025-03-23 21.48.28.log.zip](https://github.com/user-attachments/files/19410460/2025-03-23.21.48.28.log.zip)

Thank you in advance!
